/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.pindahActivity;
import Model.koneksi;
import Model.insert;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import java.awt.event.ActionEvent;

/**
 *
 * @author irwan
 */
public class Formulir extends javax.swing.JFrame {

    pindahActivity ph = new pindahActivity();
    insert ins = new insert();
    /**
     * Creates new form List
     */
    public Formulir() {
        initComponents();
        Dimension layar = Toolkit.getDefaultToolkit().getScreenSize();

        // membuat titik x dan y
        int x = layar.width / 2  - this.getSize().width / 2;
        int y = layar.height / 2 - this.getSize().height / 2;

        this.setLocation(x, y);
        
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cbTgl1 = new javax.swing.JComboBox();
        cbBln1 = new javax.swing.JComboBox();
        cbThn1 = new javax.swing.JComboBox();
        cbTgl = new javax.swing.JComboBox();
        cbBln = new javax.swing.JComboBox();
        cbThn = new javax.swing.JComboBox();
        txKtp = new javax.swing.JTextField();
        txPerjalanan = new javax.swing.JTextField();
        txJabatan = new javax.swing.JTextField();
        txNip = new javax.swing.JTextField();
        txNama = new javax.swing.JTextField();
        btnKirim = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cbTgl1.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        cbTgl1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Tanggal", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        getContentPane().add(cbTgl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 380, -1, -1));

        cbBln1.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        cbBln1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Bulan", "Januari", "Februari", "Maret", "April", "Mei", "Juni", "Juli", "Agustus", "September", "Oktober", "November", "Desember" }));
        getContentPane().add(cbBln1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 380, 140, -1));

        cbThn1.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        cbThn1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Tahun", "2030", "2029", "2028", "2027", "2026", "2025", "2024", "2023", "2022", "2021", "2020", "2019", "2018", "2017", "2016", "2015", "2014", "2013", "2012", "2011", "2010" }));
        getContentPane().add(cbThn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 380, -1, -1));

        cbTgl.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        cbTgl.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Tanggal", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        getContentPane().add(cbTgl, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 340, -1, -1));

        cbBln.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        cbBln.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Bulan", "Januari", "Februari", "Maret", "April", "Mei", "Juni", "Juli", "Agustus", "September", "Oktober", "November", "Desember" }));
        getContentPane().add(cbBln, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 340, 140, -1));

        cbThn.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        cbThn.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Tahun", "2030", "2029", "2028", "2027", "2026", "2025", "2024", "2023", "2022", "2021", "2020", "2019", "2018", "2017", "2016", "2015", "2014", "2013", "2012", "2011", "2010" }));
        getContentPane().add(cbThn, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 340, -1, -1));

        txKtp.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        getContentPane().add(txKtp, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 300, 380, -1));

        txPerjalanan.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        getContentPane().add(txPerjalanan, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 250, 380, -1));

        txJabatan.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        txJabatan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txJabatanActionPerformed(evt);
            }
        });
        getContentPane().add(txJabatan, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 210, 380, -1));

        txNip.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        getContentPane().add(txNip, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 170, 380, -1));

        txNama.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        getContentPane().add(txNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 130, 380, -1));

        btnKirim.setBackground(new java.awt.Color(0, 153, 204));
        btnKirim.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        btnKirim.setText("KIRIM");
        btnKirim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKirimActionPerformed(evt);
            }
        });
        btnKirim.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnKirimKeyPressed(evt);
            }
        });
        getContentPane().add(btnKirim, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 430, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/4.jpg"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txJabatanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txJabatanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txJabatanActionPerformed

    private void btnKirimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKirimActionPerformed
        if(txNama.getText().isEmpty()){
            JOptionPane.showMessageDialog(rootPane, "Silahkan isi nama anda terlebih dahulu!!");
        }else if(txNip.getText().isEmpty()){
            JOptionPane.showMessageDialog(rootPane, "Silahkan isi nip anda terlebih dahulu!!");
        }else if(txJabatan.getText().isEmpty()){
            JOptionPane.showMessageDialog(rootPane, "Silahkan isi jabatan anda terlebih dahulu!!");
        }else if(txPerjalanan.getText().isEmpty()){
            JOptionPane.showMessageDialog(rootPane, "Silahkan isi perjalanan dinas anda terlebih dahulu!!");
        }else if(txKtp.getText().isEmpty()){
            JOptionPane.showMessageDialog(rootPane, "Silahkan isi nomor KTP anda terlebih dahulu!!");
        }else if(cbTgl.getSelectedIndex()==0 && cbBln.getSelectedIndex()==0 && cbThn.getSelectedIndex()==0){
            JOptionPane.showMessageDialog(rootPane, "Silahkan isi tanggal pergi anda terlebih dahulu!!");
        }else if(cbTgl1.getSelectedIndex()==0 && cbBln1.getSelectedIndex()==0 && cbThn1.getSelectedIndex()==0){
            JOptionPane.showMessageDialog(rootPane, "Silahkan isi tanggal pulang anda terlebih dahulu!!");
        }
        else{
            String nama = txNama.getText();
            String nip = txNip.getText();
            String jabatan = txJabatan.getText();
            String perj_dinas = txPerjalanan.getText();
            String ktp = txKtp.getText();
        
            String bln = null;
            String bln1 = null;
        
            if(cbBln.getSelectedItem().equals("Januari")){
                bln = "01";
            }else if(cbBln.getSelectedItem().equals("Februari")){
                bln = "02";
            }else if(cbBln.getSelectedItem().equals("Maret")){
                bln = "03";
            }else if(cbBln.getSelectedItem().equals("April")){
                bln = "04";
            }else if(cbBln.getSelectedItem().equals("Mei")){
                bln = "05";
            }else if(cbBln.getSelectedItem().equals("Juni")){
                bln = "06";
            }else if(cbBln.getSelectedItem().equals("Juli")){
                bln = "07";
            }else if(cbBln.getSelectedItem().equals("Agustus")){
                bln = "08";
            }else if(cbBln.getSelectedItem().equals("September")){
                bln = "09";
            }else if(cbBln.getSelectedItem().equals("Oktober")){
                bln = "10";
            }else if(cbBln.getSelectedItem().equals("November")){
                bln = "11";
            }else if(cbBln.getSelectedItem().equals("Desember")){
                bln = "12";
            }
        
            if(cbBln1.getSelectedItem().equals("Januari")){
                bln1 = "01";
            }else if(cbBln1.getSelectedItem().equals("Februari")){
                bln1 = "02";
            }else if(cbBln1.getSelectedItem().equals("Maret")){
                bln1 = "03";
            }else if(cbBln1.getSelectedItem().equals("April")){
                bln1 = "04";
            }else if(cbBln1.getSelectedItem().equals("Mei")){
                bln1 = "05";
            }else if(cbBln1.getSelectedItem().equals("Juni")){
                bln1 = "06";
            }else if(cbBln1.getSelectedItem().equals("Juli")){
                bln1 = "07";
            }else if(cbBln1.getSelectedItem().equals("Agustus")){
                bln1 = "08";
            }else if(cbBln1.getSelectedItem().equals("September")){
                bln1 = "09";
            }else if(cbBln1.getSelectedItem().equals("Oktober")){
                bln1 = "10";
            }else if(cbBln1.getSelectedItem().equals("November")){
                bln1 = "11";
            }else if(cbBln1.getSelectedItem().equals("Desember")){
                bln1 = "12";
            }
        
            String tglPergi = cbThn.getSelectedItem()+bln+cbTgl.getSelectedItem();
            String tglPulang = cbThn1.getSelectedItem()+bln1+cbTgl1.getSelectedItem();
            
            JOptionPane.showMessageDialog(rootPane, ins.data(nama, nip, jabatan, perj_dinas, ktp, tglPergi, tglPulang));
        }
    }//GEN-LAST:event_btnKirimActionPerformed

    private void btnKirimKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnKirimKeyPressed
//        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
//            JOptionPane.showMessageDialog(rootPane, "Mantapp!!");
//        }
    }//GEN-LAST:event_btnKirimKeyPressed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Formulir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Formulir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Formulir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Formulir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
////        java.awt.EventQueue.invokeLater(new Runnable() {
////            public void run() {
////                new Formulir().setVisible(true);
////            }
////        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKirim;
    private javax.swing.JComboBox cbBln;
    private javax.swing.JComboBox cbBln1;
    private javax.swing.JComboBox cbTgl;
    private javax.swing.JComboBox cbTgl1;
    private javax.swing.JComboBox cbThn;
    private javax.swing.JComboBox cbThn1;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField txJabatan;
    private javax.swing.JTextField txKtp;
    private javax.swing.JTextField txNama;
    private javax.swing.JTextField txNip;
    private javax.swing.JTextField txPerjalanan;
    // End of variables declaration//GEN-END:variables
}
